// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Votify.Infrastructure.Persistence;

#nullable disable

namespace Votify.Infrastructure.Migrations
{
    [DbContext(typeof(VotifyDbContext))]
    [Migration("20260427151050_AddImagenUrlToEvento")]
    partial class AddImagenUrlToEvento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Votify.Infrastructure.Persistence.Entities.ComentarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("Autor_Id")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("Proyecto_Id")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("Votify.Infrastructure.Persistence.Entities.EventoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("evento");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Descripcion = "Evento de programación de 48 horas para crear soluciones innovadoras.",
                            FechaFin = new DateTime(2026, 4, 29, 15, 10, 49, 601, DateTimeKind.Utc).AddTicks(1373),
                            FechaInicio = new DateTime(2026, 4, 26, 15, 10, 49, 601, DateTimeKind.Utc).AddTicks(1123),
                            ImagenUrl = "images/hackathon-cover.png",
                            Nombre = "Hackathon Anual 2026"
                        },
                        new
                        {
                            Id = new Guid("f6e5d4c3-b2a1-4f5e-9d8c-7b6a5e4d3c2b"),
                            Descripcion = "Presentación de proyectos finales de la asignatura Proyectos de Software.",
                            FechaFin = new DateTime(2026, 5, 7, 15, 10, 49, 601, DateTimeKind.Utc).AddTicks(1696),
                            FechaInicio = new DateTime(2026, 5, 2, 15, 10, 49, 601, DateTimeKind.Utc).AddTicks(1695),
                            ImagenUrl = "images/feria-cover.png",
                            Nombre = "Feria de Proyectos PSW"
                        });
                });

            modelBuilder.Entity("Votify.Infrastructure.Persistence.Entities.ProyectoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("Categoria_Id")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Equipo_Id")
                        .HasColumnType("text")
                        .HasColumnName("equipo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("proyecto");
                });

            modelBuilder.Entity("Votify.Infrastructure.Persistence.Entities.VotacionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Comentarios")
                        .HasColumnType("boolean")
                        .HasColumnName("comentarios");

                    b.Property<bool>("EsAnonima")
                        .HasColumnType("boolean")
                        .HasColumnName("EsAnonima");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("LimiteProy")
                        .HasColumnType("integer")
                        .HasColumnName("limite_proy");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("votacion");
                });

            modelBuilder.Entity("Votify.Infrastructure.Persistence.Entities.VotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.Property<Guid>("VotacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("votacion_id");

                    b.Property<Guid?>("VotanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("votante_id");

                    b.HasKey("Id");

                    b.ToTable("votos");
                });
#pragma warning restore 612, 618
        }
    }
}
